### ISSUE TITLE
Can't start client with kanan launcher

### ISSUE THREAD

**Issue by Arceni** [cursey/kanan-new#182]
Somewhere after 23.05.2021 launcher started to show error "failed to send request". I can log in by nexon launcher and i'm pretty sure that it isn't caused by nexon verification code.

**Comment by cursey** [comment]
Everything is working fine for me still so I've pushed a commit that should give more information about what is failing (589137308627521e0d49e723c95a7203ef3b8c3c). Please download the latest artifact from AppVeyor (https://ci.appveyor.com/project/cursey/kanan-new/build/artifacts) and let me know what the new error is.

**Comment by Priestbilly** [comment]
Thank you for looking into this. The new error I'm receiving when trying to launch using Launcher is: "Failed to send request: A security error occurred". I've taken the following troubleshooting steps:

1) Signed into the account via Nexon Launcher, and removed it as a trusted device. The signed in again making sure to enable "Trust This Device".  Same error.

2) Put the newest commit of Kanan into a separate folder without any previous settings/profiles of my current Kanan install and tried to launch from there. Same error.

Please let me know if there's any other steps or information I can provide.

**Comment by cursey** [comment]
@Priestbilly is your system clock set correctly?

**Comment by Priestbilly** [comment]
@cursey Yes, I went into Time and Date management and synced it with internet time just now to double-check, still receiving the same error.

**Comment by cursey** [comment]
I've added the last URL requested to the error messages (7b161f53be9c7359bddef8a9ef1425879a4e9ed9). Could you please download the latest artifact from AppVeyor again (https://ci.appveyor.com/project/cursey/kanan-new/build/artifacts) and let me know what the new error is.

**Comment by dackmagic** [comment]
@cursey
 [https://www.nexon.com/api/account/v1/no-auth/login/launcher] 

Failed to send request: A security error occurred

**Comment by Priestbilly** [comment]
@cursey 

I can confirm I am receiving the same error as above:

```
[https://www.nexon.com/api/account/v1/no-auth/login/launcher]

Failed to send request: A security error occurred
```

**Comment by Priestbilly** [comment]
Following up on this with additional troubleshooting steps I've taken:

* Completely reinstalled both Nexon Launcher and Mabinogi from scratch onto a different hard drive. Previous install was deleted. Removed trusted device from fresh Nexon Launcher, logged out, and signed back in using the "Remember this device" option. Same error.

* Had a friend sign in using current build of Kanan  and my account. Registered as a trusted device and signed in using Kanan Launcher with no issues.

The specs between my PC and my friend's PC are not radically different, though she is running Windows 10 while I am running Windows 7, if that helps.

**Comment by shyunknownplayer** [comment]
i am using window 7

**Comment by tsutsutsutsu** [comment]
Downloaded this on Win7 and am experiencing the issue as well.  Very much appreciate the work put into this!  Have there been any updates since the initial reporting?

**Comment by cursey** [comment]
Seems like the issue may be related to Windows 7. I do not have Windows 7 to test this.

**Comment by Priestbilly** [comment]
Just installed Windows 10, and used the same install of Nexon Launcher and of Mabinogi to use Kanan Launcher. Launched immediately without ever having to sign in to each account using Nexon Launcher. Definitely seems to be a Windows 7 issue.

**Comment by cursey** [comment]
My guess is that this is related to the Windows 7 version of `WinHttp` (the API Kanan Launcher uses to make web requests) having different TLS settings (read: old/insecure) that nexon has decided to stop supporting on their login servers. I may look into this more but I doubt I'll be motivated enough to setup a Windows 7 VM just to fix this since Windows 7 is no longer an officially supported Microsoft product.

**Comment by Arceni** [comment]
Used this:
https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392
Installed KB3140245, used easyfix and enabled TLS 1.2 at the SChannel component level.
Now client is starting normally.

**Comment by cursey** [comment]
I've pushed a commit (177f97f206e2ab86d7e5982b916b0e393b31cbcc) and created a release (https://github.com/cursey/kanan-new/releases/tag/2021.6.11) that specifically sets the WinHttp secure protocols option to TLS 1.1 or 1.2. This *hopefully* fixes the issue on Windows 7 without needing to install the update @Arceni mentioned but I have not tested it. If this still does not fix it then you should just follow what @Arceni did above.

**Comment by Poypoyer** [comment]
I'm having this error showing everytimes i try to open the client via kanan launcher, i did open the loader first as well. I can also launch the game and having the loader on and it works fine, I can't launch a new client with Kanan Launcher. I did setup the client path to Client.exe in the appdata folder.[https://gyazo.com/babfc1be879f601cafcebea217779b7d](url)
[https://gyazo.com/f0d60cfa1c8b91f7f1d459187479576f](url)

**Comment by yeongbin-jo** [comment]
![image](https://user-images.githubusercontent.com/44139236/193422443-d872597f-4ad7-41f1-85ba-274854e13253.png)

I got same error on Windows 10 (21H1) 😭
